#!/usr/bin/env python
import sys

from pylog4all import l4a_add,l4a_search,l4a_tail


commands = {'add': l4a_add.main, 'search': l4a_search.main, 'tail': l4a_tail.main}

def print_usage():
    print ("Usage: " + sys.argv[0] + " " + str(commands.keys()))
    sys.exit(-2)


if __name__ == '__main__':
    if len(sys.argv) == 1:
        print_usage()
    else:
        if not sys.argv[1] in commands:
            print ("Command not found")
            print_usage()
        else:
            commands[sys.argv[1]]()